# Python Variables Practice

ðŸ”¹ This notebook contains 25 exercises (from easy to hard) to help you practice Python variables.

ðŸ”¹ This notebook (only problems) was generated by ChatGPT.

ðŸ”¹ The problems were solved through my own efforts.

---

1. Create a variable called `name` and assign your name to it.

In [1]:
name = 'Mohammad'

2. Assign the value 25 to a variable named `age`.

In [2]:
age = 25

3. Create a variable `is_student` and assign it a boolean value.

In [3]:
is_student = True

4. Assign the value 3.14 to a variable called `pi`.

In [4]:
pi = 3.14

5. Create two variables `x` and `y`, assign any numbers, and print their sum.

In [6]:
x, y = 5, 20

sum_xy = x + y

print(sum_xy)

25

6. Swap the values of two variables `a` and `b`.

In [7]:
a, b = 3, 7

a, b = b, a

print(f'a: {a} & b: {b}')

a: 7 & b: 3

7. Assign your birth year to a variable and calculate your current age.

In [18]:
birth_year = 2000

age = 2025 - birth_year

print('Age:', age)

Age: 25

8. Define three variables in one line: `a`, `b`, and `c` with values 1, 2, and 3.

In [10]:
a, b, c = 1, 2, 3

9. Create a string variable that includes both single and double quotes.

In [11]:
text = "I'm a Data Science student."

text

"I'm a Data Science student."

10. Assign a multiline string to a variable named `story`.

In [22]:
story = """A data scientist once faced a messy, incomplete datasetâ€”rows of missing values and noise.  
Instead of giving up, she cleaned, transformed, and modeled it with patience.  
Her insights uncovered hidden patterns that revolutionized her companyâ€™s strategy.  
Lesson: Even chaos can reveal truth, with the right analysis and perseverance."""  

print(story)

A data scientist once faced a messy, incomplete datasetâ€”rows of missing values and noise.
Instead of giving up, she cleaned, transformed, and modeled it with patience.
Her insights uncovered hidden patterns that revolutionized her companyâ€™s strategy.
Lesson: Even chaos can reveal truth, with the right analysis and perseverance.

11. Create a variable `height_cm` and convert it to meters in another variable.

In [12]:
height_cm = 180

height_m = height_cm / 100

print(height_m)

1.8

12. Assign your first and last names to two variables, then combine them into a full name.

In [15]:
first_name = 'Mohammad'

last_name = 'Alam'

full_name = first_name+ ' ' + last_name

print(full_name)

Mohammad Alam

13. Create a variable `temp_celsius` and convert it to Fahrenheit.

In [16]:
temp_celsius = 25

temp_fahrenheit = (temp_celsius * 9 / 5) + 32

print(temp_fahrenheit)

77.0

14. Create a list of your top 3 favorite colors and assign it to `colors`.

In [17]:
colors = ['Black', 'Navy Blue', 'Olive']

colors

['Black', 'Navy Blue', 'Olive']

15. Assign a dictionary of your name, age, and city to a variable `person`.

In [19]:
person = {
    'name'  : 'Mohammad Khorshed Alam',
    'age'   : 25,
    'city'  : 'Dhaka'
}

person

{'name': 'Mohammad Khorshed Alam', 'age': 25, 'city': 'Dhaka'}

16. Use a variable to hold the result of `5 + 3 * 2` and print it.

In [23]:
a, b, c = 5, 3, 2

result = 5 + 3 * 2

result

11

17. Create a variable `sentence` and count the number of characters in it.

In [24]:
sentence = 'Data is the new oil.'

len(sentence)

20

18. Take a float value and assign it to a variable, then convert it to an integer.

In [26]:
float_value = float(input('Enter a float number: '))

int_value = int(float_value)

int_value

12

19. Use `input()` to ask the user's name and store it in a variable.

In [27]:
name = input('Name: ')

name

'Mohammad'

20. Define two variables, `length` and `width`, and calculate area of a rectangle.

In [29]:
length, width = 10, 5

area = length * width

area

50

21. Assign a list of numbers to a variable and find their average.

In [33]:
numbers = [5, 9, 7, 2, 12, 6, 11, 16]

avg = sum(numbers) / len(numbers)

avg

8.5

22. Store a file path in a variable and print its file extension.

In [39]:
file_path = 'user/variables.ipynb'

file_extension = file_path.split('.')[-1]

print('File Extension:', file_extension)

File Extension: ipynb

23. Create a variable with a complex number and print its real and imaginary parts.

In [43]:
complex_num = 3+2j

real_part = complex_num.real
imaginary_part = complex_num.imag


print(f'Real part: {real_part}\nImaginary part: {imaginary_part}')

Real part: 3.0
Imaginary part: 2.0

24. Store the result of checking if 15 is greater than 10 in a variable.

In [44]:
result = 15 > 10

result

True

25. Use a variable to build and print a formatted message using f-strings.

In [46]:
a, b, c = 25, 50, a+b

print(f'{c} is the sum of {a} and {b}!')

75 is the sum of 25 and 50!