# Python Arrays Practice (with array module)

This notebook includes **20 exercises** (easy to hard) to help me gain mastery over **Python Arrays** using the built-in `array` module.

ðŸ”¹ This notebook (only problems) was generated by ChatGPT.

ðŸ”¹ The problems were solved through my own efforts.

---

### 1. Import the `array` module and create an integer array with values [1, 2, 3, 4, 5].

### 2. Append a new element (6) to the array.

### 3. Insert an element (0) at the beginning of the array.

### 4. Remove the element 3 from the array.

### 5. Reverse the array.

### 6. Access the third element of the array.

### 7. Find the index of element 4.

### 8. Count how many times a value occurs in the array.

### 9. Convert the array to a normal Python list.

### 10. Create a function that returns the maximum and minimum element in an array.

### 11. Multiply each element in the array by 2.

### 12. Find the sum of all elements in the array.

### 13. Create an array from a list of even numbers between 1 and 20.

### 14. Given an array, find and return all elements greater than the average.

### 15. Check if a given number exists in an array.

### 16. Merge two arrays into a single array.

### 17. Create a function that removes all duplicates from an array.

### 18. Sort the array in ascending order without using `.sort()` method.

### 19. Rotate the array to the left by 2 positions.

### 20. Write a program to find the second largest element in the array.