# Python Sets Practice

This notebook includes **25 exercises** (easy to hard) to help me master **Python Sets**.

ðŸ”¹ This notebook (only problems) was generated by ChatGPT.

ðŸ”¹ The problems were solved through my own efforts.

---

### 1. Create a set of numbers from 1 to 5.

### 2. Add a new element to a set.

### 3. Remove an element from a set.

### 4. Clear all elements from a set.

### 5. Check if an element exists in a set.

### 6. Find the union of two sets.

### 7. Find the intersection of two sets.

### 8. Find the difference between two sets.

### 9. Find the symmetric difference between two sets.

### 10. Convert a list with duplicates into a set.

### 11. Given two sets, check if they are disjoint.

### 12. Check if one set is a subset of another.

### 13. Check if one set is a superset of another.

### 14. Pop an arbitrary element from a set.

### 15. Copy a set into a new set.

### 16. Given a sentence, find all unique characters.

### 17. Remove all vowels from a sentence using sets.

### 18. Find common items in two lists using sets.

### 19. Find elements in list A not in list B using sets.

### 20. Create a set of even numbers from 1 to 20.

### 21. Write a function that returns the intersection of all sets in a list.

### 22. Given a list of strings, return all unique words.

### 23. Find the first non-repeating character in a string using set logic.

### 24. Write a program to find duplicate elements in a list using sets.

### 25. You are given two datasets of users who bought product A and B. Find users who bought both, only A, and only B.